[tool.poetry]
name = "disrpt-utils"
version = "0.1.1"
description = ""
authors = ["sileod"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
